### ISSUE TITLE
Driver was set to chrome instead of gecko driver 

### ISSUE THREAD

**Issue by sureshk2a** [krishnansiva07/TestAutomation#1]
`else if (browserName.equals(Constant.browserNamefirefox)) {
			String path = Constant.currentDir + Constant.driversFolderName
					+ Constant.firefoxDriverName;
			System.setProperty("webdriver.chrome.driver", path);`

**Comment by krishnansiva07** [comment]
Change the system property

**Comment by sureshk2a** [comment]
Been watching this design lately, would like to see further development
